#!/usr/bin/env bash

echo "Testing Tengine current configuration..."
nginx -t && nginx -s reload

echo "Checking if there is any container requiring SSL..."
if grep ACME_DOMAINS /etc/nginx/conf.d/default.conf
then
    for acme_domains in $(grep ACME_DOMAINS /etc/nginx/conf.d/default.conf | cut -d ' ' -f 2);
        do
            d=$(echo "$acme_domains" | cut -d , -f 1)

            echo "Getting certificates for $acme_domains..."
            $LE_WORKING_DIR/acme.sh --home $LE_WORKING_DIR --config-home $LE_CONFIG_HOME --issue \
            -d $acme_domains \
            --nginx \
            --fullchain-file "/etc/nginx/certs/$d.crt" \
            --key-file "/etc/nginx/certs/$d.key" \
            --reloadcmd "nginx -t && nginx -s reload"
        done

    echo "Saving new Tengine configuration..."
    docker-gen /app/default.conf /etc/nginx/conf.d/default.conf

    echo "Reloading Tengine with new configuration..."
    nginx -t && nginx -s reload
else
    echo "No containers requiring SSL, skipping acme.sh"
fi
