#!/usr/bin/env sh

_OUTPUT_="$0"

acme() {
    echo "reloading tengine with old configuration"
    nginx -t && nginx -s reload

    echo "checking if there is any server requiring SSL"
    if grep ACME_DOMAINS /etc/nginx/conf.d/default.conf
    then
        for d_list in $(grep ACME_DOMAINS /etc/nginx/conf.d/default.conf | cut -d ' ' -f 2);
            do
                d=$(echo "$d_list" | cut -d , -f 1)

                echo "getting certificates for $d_list"
                /acme.sh/acme.sh --home /acme.sh --config-home /acmecerts --issue \
                -d $d_list \
                --nginx \
                --fullchain-file "/etc/nginx/certs/$d.crt" \
                --key-file "/etc/nginx/certs/$d.key" \
                --reloadcmd "nginx -t && nginx -s reload"
            done

        echo "applying new tengine configuration"
        docker-gen /app/default.conf /etc/nginx/conf.d/default.conf
    fi

    echo "reloading tengine with new configuration"
    nginx -t && nginx -s reload
}

"$@"
